version: "3"
services:
  codeigniter-3:
    build: .
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/sg2slim
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: sitekg
      MYSQL_PASSWORD: Mrcuex11!
      MYSQL_ROOT_PASSWORD: Mrcuex11!
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Mrcuex11!
    depends_on:
      - db

volumes:
  db_data:
